version: 2

project_name: sony-remote

builds:
  - skip: true

archives:
  - meta: true

checksum:
  disable: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dist: build